Repository FRONTENDBOOTCAMP-14th/js-project-team-5, pull requests merged in 2025-08, with the labels that each got.

#79 feat: 산성비 게임 페이지 및 기능 구현
  public/assets/audio/sfx/droplet-sound.mp3
  public/assets/audio/sfx/droplet-sound2.mp3
  src/pages/acidrain/acidrain.css
  src/pages/acidrain/acidrain.html
  src/pages/acidrain/acidrain.js
Labels: fix

#99 [hotfix] eslint 검사 및 버그 수정
  README.md
  public/assets/images/readme-main.png
  public/assets/images/readme-select.png
  public/assets/images/readme-window.png
  src/components/modal/modal.js
  src/components/modal/pause-modal.js
  src/components/modal/pause-modal/acidrain-pause.js
  src/components/modal/pause-modal/defense-pause.js
  src/components/modal/pause-modal/quiz-pause.js
  src/pages/game-defence/defence.html
  src/pages/game-defence/defence.js
  src/pages/game-quiz/quiz-in-game.js
  src/pages/mole-game/in-game/in-game.css
Labels: hotfix, fix

#106 [docs] README.md 수정
  README.md
  public/assets/images/IceJack.png
  public/assets/images/changyeopbaek.png
  public/assets/images/hana12051.jpg
  public/assets/images/jeonjyeon.png
Labels: docs
