Repository FRONTENDBOOTCAMP-14th/js-project-team-5, pull requests merged in 2025-07, with the labels that each got.

#9 feat: 색상 및 글자 크기 루트 변수 설정
  src/styles/common/theme.css
Labels: chore

#25 [feat] 모달 컴포넌트
  index.html
  public/assets/icons/close.svg
  public/assets/icons/favicon.ico
  public/assets/icons/monitor_neck.png
  src/components/modal/modal.css
  src/components/modal/modal.html
  src/components/modal/modal.js
  src/components/test.html
  src/style.css
  src/styles/components/index.css
  src/styles/components/test.css
Labels: feat, refactor, style

#66 [refactor] 중간 점검 피드백 반영
  .prettierrc.cjs
  customLib.js
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/fonts/KIMM.css
  src/components/booting/booting.html
  src/components/button/button.html
  src/components/card/card.html
  src/components/game-choice-header/game-choice-header.html
  src/components/header/in-game-header.html
  src/components/input/input.css
  src/components/input/input.html
  src/components/modal/modal.html
  src/components/monitor/monitor.html
  src/components/slider/slider.html
  src/components/window/window.html
  src/pages/game-landing/acidrain-landing.html
  src/pages/game-landing/defense-landing.html
  src/pages/game-landing/quiz-landing.html
  src/pages/game-landing/whack-landing.html
  src/pages/game-select/game-select.css
  src/pages/game-select/game-select.html
  src/pages/main-start-page/main-start-page.html
  src/pages/main-start-page/main-start-script.js
  src/pages/main-start-page/main-start-style.css
  src/pages/test.html
  src/styles/common/base.css
  vite.config.js
Labels: refactor, fix, chore
